CREATE TABLE PIN.AC_REPASSE_IPC (
    BILLINFO NUMBER(38,0),
    ACCOUNT NUMBER(38,0),
    PURCHASED_PRODUCT_OBJ NUMBER,
    CRM_PRODUCT_ID VARCHAR2(60),
    VALOR_ANTIGO NUMBER(14,2),
    VALOR_NOVO NUMBER(14,2),
    FATOR_AJUSTE NUMBER,
    DATA_AJUSTE NUMBER,
    STATUS NUMBER
);

CREATE INDEX id_sequence ON PIN.AC_REPASSE_IPC (BILLINFO, ACCOUNT, PURCHASED_PRODUCT_OBJ );