
CREATE USER IPCUSERTESTE IDENTIFIED BY 123456;

CREATE TABLE IPCUSERTESTE.AC_REPASSE_IPC_TESTE (
    BILLINFO NUMBER(38,0),
    ACCOUNT NUMBER(38,0),
    PURCHASED_PRODUCT_OBJ NUMBER,
    CRM_PRODUCT_ID VARCHAR2(60),
    VALOR_ANTIGO NUMBER(14,2),
    VALOR_NOVO NUMBER(14,2),
    FATOR_AJUSTE NUMBER,
    DATA_AJUSTE TIMESTAMP,
    STATUS NUMBER DEFAULT 0
);

GRANT SELECT, INSERT, UPDATE ON SCHEMA IPCUSERTESTE TO PIN;